export const ADD_FROM_FORM_TO_STATE = "MAIN/ADD_FROM_FORM_TO_STATE"
export const SHOW_GUEST_BLOCK = "MAIN/SHOW_GUEST_BLOCK"
export const HIDE_GUEST_BLOCK = "MAIN/HIDE_GUEST_BLOCK"
export const ADD_TO_ROOM = "MAIN/ADD_TO_ROOM"
export const TAKE_AWAY_TO_ROOM = "MAIN/TAKE_AWAY_TO_ROOM"
export const ADD_TO_ADULT = "MAIN/ADD_TO_ADULT"
export const TAKE_AWAY_TO_ADULT = "MAIN/TAKE_AWAY_TO_ADULT"
export const ADD_TO_CHILDREN = "MAIN/ADD_TO_CHILDREN"
export const TAKE_AWAY_TO_CHILDREN = "MAIN/TAKE_AWAY_TO_CHILDREN"
export const SET_CHECK_IN = "MAIN/SET_CHECK_IN"
export const SET_CHECK_OUT = "MAIN/SET_CHECK_OUT"
export const MAIN_PAGE_INPUT_CHANGE = "MAIN/MAIN_PAGE_INPUT_CHANGE"
export const MAIN_PAGE_INPUT_CHANGE_FOR_EMAIL =
  "MAIN/MAIN_PAGE_INPUT_CHANGE_FOR_EMAIL"

export const CATALOG_TO_GRID = "CATALOG/CATALOG_TO_GRID"
export const CATALOG_TO_LIST = "CATALOG/CATALOG_TO_LIST"
export const CATALOG_LOADING_ALL = "CATALOG/LOADING_ALL"
export const CATALOG_CHANGE_PRICE_RANGE = "CATALOG_CHANGE_PRICE-RANGE"
export const CATALOG_CHANGE_PROPERTY_TYPE_HOTEL =
  "CATALOG/CATALOG_CHANGE_PROPERTY_TYPE_HOTEL"
export const CATALOG_CHANGE_PROPERTY_TYPE_APARTMENT =
  "CATALOG/CATALOG_CHANGE_PROPERTY_TYPE_APARTMENT"
export const CATALOG_FILTER_HOTEL = "CATALOG/CATALOG_FILTER_HOTEL"
export const CATALOG_FROM_MAIN_PAGE = "CATALOG/FROM_MAIN_PAGE"
export const CATALOG_SET_FILTERED = "CATALOG/CATALOG_SET_FILTERED"
export const CATALOG_UNSET_FILTERED = "CATALOG/CATALOG/UNSET_FILTERED"

export const SIGNUP_INPUT_CHANGE = "LOGIN/SIGNUP_INPUT_CHANGE"
export const SIGN_IN_INPUT_CHANGE = "LOGIN/SIGN_IN_INPUT_CHANGE"
export const REGISTER_CHANGE = "LOGIN/REGISTER_CHANGE"
export const LOGIN_CHANGE = "LOGIN/LOGIN_CHANGE"
export const NOT_LOGIN = "LOGIN/NOT_LOGIN"
export const LOGOUT_CHANGE = "LOGIN/LOGOUT_CHANGE"

export const REPRESENTATIVE_INPUT_CHANGE =
  "REPRESENTATIVE/REPRESENTATIVE_INPUT_CHANGE"
export const REPRESENTATIVE_LOAD_COUNTRY =
  "REPRESENTATIVE/REPRESENTATIVE_LOAD_COUNTRY"
export const REPRESENTATIVE_SELECT_COUNTRY_LOAD_CITY =
  "REPRESENTATIVE/REPRESENTATIVE_SELECT_COUNTRY_LOAD_CITY"
export const REPRESENTATIVE_RESET_FORM =
  "REPRESENTATIVE/REPRESENTATIVE_RESET_FORM"
export const REPRESENTATIVE_LOADING_HOTELS =
  "REPRESENTATIVE/REPRESENTATIVE_LOADING_HOTELS"
export const REPRESENTATIVE_LOADING_HOTEL_BY_ID =
  "REPRESENTATIVE/REPRESENTATIVE_LOADING_HOTEL_BY_ID"
export const REPRESENTATIVE_SELECT_PROPERTY_TYPE =
  "REPRESENTATIVE/REPRESENTATIVE_SELECT_PROPERTY_TYPE"

export const HIDE_LOADER = "APP/HIDE_LOADER"
export const SHOW_LOADER = "APP/SHOW_LOADER"
